name: form_field_validator
description: A straightforward flutter form field validator that provides common validation options.
version: 1.0.1
author: Milad Akarie <milad.akarie@gmail.com>
homepage: https://github.com/Milad-Akarie/form_field_validator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <=1.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
